version: '3.8'

services:
  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    environment:
      - DSN=postgres://me:root@auth-db/authdb?sslmode=disable
      - AUTH_SERVICE_PORT=50051
      - OTP_SERVICE_ADDRESS=otp_service:50052
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/
    ports:
      - "50051:50051"
    depends_on:
      - auth-db
      - rabbitmq
      - otp_service

  otp_service:
    build:
      context: ./otp_service
      dockerfile: Dockerfile
    environment:
      - TWILIO_ACCOUNT_SID=ACad6b3583760bc9503f4168895ec58aad
      - TWILIO_AUTH_TOKEN=e4137e1e5be07acac1dc32f53bc57911
      - TWILIO_FROM_PHONE=+923104747899
      - TWILIO_SERVICES_ID=VA25c3799dc58795c358d2d0358e29aa6f
      - OTP_SERVICE_PORT=50052
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/
    ports:
      - "50052:50052"
    depends_on:
      - rabbitmq

  auth-db:
    image: postgres:13
    environment:
      POSTGRES_USER: me
      POSTGRES_PASSWORD: root
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  auth-db-data:
